---
abstract: 'Release tests making sure no char encoding problems is in the code'
author:
  - 'Alexei Znamensky <russoz@cpan.org>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-MojibakeTest
requires:
  Dist::Zilla::Plugin::InlineFiles: 0
  Moose: 0.99
  Test::Mojibake: 0
  namespace::autoclean: 0.09
resources:
  bugtracker: http://github.com/russoz/Dist-Zilla-Plugin-MojibakeTest/issues
  repository: git://github.com/russoz/Dist-Zilla-Plugin-MojibakeTest.git
version: 0.001
